language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rake ci:tests
notifications:
  email: false
env:
  global:
  - secure: VzE8PurllLEbvYH+h2kUtGW2f6tP2Tzfz4QV+WKst4MJm73T7VFB/a+rMVrLM7yXIxNX2GNz0cHtbK675KCgSudJ6JHPC+x2PK1qA6SiH66bAhRL1EMZVHifx0zZTnXDbq3LlJjUDTWsyjLDgZV98Qvw0aq/OUreqZBFaDlIAZunEo3VH3zUi4S2iQiUfEMfZwQUu9W9ffs4nQUOVvdS1ldVWPPQBuHY2jCMztXoutbFnBEyWTy9K5QkI7RsyXhLA5BAlc+FNFzCgU02zcIy7hA9A+wugFPKVLiH0R9V8DW4RmJEeKRjX8gxY4oW9jUr4Z1d4jfs0Z/uTUm0ziRb65HKYr/3w0YjadKtn3Zz+enCOm/KkRgr3xh1AJKTZV9sPXQCeffktx6K/R2nRen6WwAoUVx7qQ22g+cj1Cb/mj79favaT5HsZxuHrwRTpZx4Jr2n9RRv85/0i3fPu7m2ir6AdDlul9dOPUZG/g4QbirgJ/Ok1nLU6jhWeLgMoXzMdgoxlPWgs7/KERLlcuE33wWjs89n7znUI73gyTD7BAjiOOJsVG8wocGwnk+tr+IlSiHStn3r1oez0bYOuzZ0jyhhUAXSwAp5dAAFly/A0mwlOLKxVFQHByl8pRcLSr8HsNZTOyNv4OzlRrOQPubHXZhJ0roelneI+i/+Ewg7xLY=
  - secure: FsxEM9oW40X8ICdDm/3K57GgKPkUVkc2kvm+uHPu3q0njdll0FWcxOhFCl3PPRxpkCm1UWoMd3JWrhnEtT6e3cWdPZho+gBXduTo6LsLqrvslJ7/7sPMc6/Xu1kIWMnYRDOvFWZUWfOPpZGcbI9PZuJPoFyqy9zd5dyVp/lEQvjF3hPo9nz72yFAtmE78AYUWtLOJehPzQdoY22WNQnQMYhzfJMVPAj2qCabGlEKt2blA1kF+hT7o1n2VG9pNJYAusqUTdZbcRYTT8KYJ112ADDgfo4F7Sg8nV3kxgpmhe0OVMWjHTH+acfCu3cqWB6+3yPo+Gwp7YjXB/b/wRC+ObpciBzwZnKK9tIai95QyO4QvBgeUdNiQyOlqnLMNmw43MqEvHIekmCocpSdCxfeI5S4QT7QhGOLm1+65ldY/Leae+xv6ayb/tfsdH+cnPvo2NsdMbQ3epuUwvfFpzbbHnGtAfpiV0JFneqIJT+ACM6+y73ZjtlVs9qfLkayfIJvAKBQnGFFjkdyYOTiuDBo1xSje5NOxM7H6DtAzyEIHZzkzYrO6UZD4qsoOWlo92/XoY8cwWLCpY0Rq/zunZzcJyFQ4lumVlnmlYOpc18x6jRaMG2mZcUfZ+Dm6x5b4RVZbPLv8owzdeFJGMYLImDSfKZzoC7WK/MJ6OpgH2SyVqY=
