language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rake ci:tests
notifications:
  email: false
env:
  global:
  - secure: RbuynbHPlwrf5yh9CNuvWljk0KyGZNLBuq3P/ZrUXzOdR5WK+xtWFJzs7uTtrsX5pn1kos0GUNWA7p8IXlzJKdmziPFayPy+XE3D38XLUUep7eaL6jg4ruTNJ6eQul1bF9vjzO7krU6b6kKqkdMs5OHmNcp/KmcKIPe39Po0XDo189CVb6hHeu2h0MMzHGgtqfD96V2xLZOPAMB9Qh/CiT2MnomkIhwTlpRuuGFy7U4cUSbl/x6TnkZS1kmGPne6agoPMz5rF2btsx6JAXzG86c84Hqpyg9WCHKDZOpoKgenBpR/N0ltoNNsql7f7CsxMI+rFLQ6KOLbW1UAQG2X4HHlj0w2nQHgxwbrx68xKZqEM7euNxSgcJuzdtdL4mmZmWDyWFdU3LTr1MJuXw/8fIvKAF605+Rte3YULhuXhoC5nO5BTxhDe1p5GhgXUsfHOyydgu3u/nzAtypNblyVAjAptQfhwf/nyoPVGDlBkQPmQDZkcSG0g2D29BlxTP5gPFrYO2ZbgBxsYxSgc9bOX7qJ50mYm3Yx+p5J4h+DhKILj1nPSDpEvAIob5O3Kmkrp68lD+OK9/EFKro/zVCzwFjr5YplS/9iHK4WVpUxSY4n/TTc/x0+RESzRr9C3Lwbigx/hevczgHQlHr6BTCR8VYzhaO25PkMh/by+sE8JOw=
  - secure: H/kJqXqz/ioX29Q7XMLKmwXG3T+bI+eoe4S4FOW+p87n5StjC3L0CoTh+QpLB+61unv45xLgDNMpLnHEHeR3kDJWRDMjoOys+tNH0kyLDuE2beqh7Dbnt9UPutZckAZouZ4wvQPQn5l8J45kQYBu0EYYnXFyp0BJBmpO+KsFYB+QcwnkxuwGX403N43HjnHhY7FMLU3jJ4ACIY6IqQlvxa2ytFEEBZEnfGTpqjpFUW82g5eKI3VpRr2RxdRthMOLHvI6IIjvL0TEKsmtp2TIIJ+ORQtsammuY1CmRk+BfzbK85pIk/0rxeplA4FISuw8oeV4AGzxZayC2v3hUQ+jrZs2QLLjfdAkFuhaawe/TGwFQSMoAYcRz1QO8DPvbzArjmKuNxNVbjU85CBnzLMGivHyFucmHNPGylCPuICPuG9MvZrg+4i7f5Wzv1GVBDCK6SLYBeaZd15Y2YQ40D7oFvZE5wTOVnPidYQ48HfzONUsRcKkAgIllzciFSpV4MnS4092Nl3FavtCdtakE2UHjL8FNKK9N5OZb9FfBJvmBxqfOPl6RLpZqDgPtVcbDDG5S086Kd2DZZBH6IagDueSNpQ3x5GrA1o/Sg8HtzF9T2lWc5h08M7kxApCkHcSFNsMiNrey50bs6t+JAUrYhn2c+/9Co5kM7xaQNXBZCcs3iI=
